version: '2'
volumes:
  shareddata:
services:
  webserver:
    build: ./webserver
    privileged: true
    volumes:
      - 'shareddata:/data:ro'
    ports:
      - 80:80
      - 5050:5050
    restart: always

  tcp:
    build: ./tcpserver
    privileged: true
    volumes:
      - 'shareddata:/data'
    ports:
      - 5003:5003
    restart: always
